sudo: required

services:
      - docker
addons:
  apt:
    packages:
      - docker-ce

before_install:
    - ./contrib/ci.sh
    
script:
    - make

after_success:
    - if [ -z $DOCKER_NS ] ; then
        export DOCKER_NS=functions;
        fi
    - if [ ! -z "$TRAVIS_TAG" ] ; then 

	echo "Travis tag: $TRAVIS_TAG"

        docker tag $DOCKER_NS/faas-swarm:latest-dev $DOCKER_NS/faas-swarm:$TRAVIS_TAG;
        docker login -u=$DOCKER_USERNAME -p=$DOCKER_PASSWORD;
        docker push $DOCKER_NS/faas-swarm:$TRAVIS_TAG;

        docker tag $DOCKER_NS/faas-swarm:latest-dev quay.io/$DOCKER_NS/faas-swarm:$TRAVIS_TAG;
        docker login quay.io -u=$QUAY_USERNAME -p=$DOCKER_PASSWORD;
        docker push quay.io/$DOCKER_NS/faas-swarm:$TRAVIS_TAG;

        fi
