sudo: required

services:
      - docker
addons:
  apt:
    packages:
      - docker-ce

before_install:
    - ./contrib/ci.sh
    
script:
    - make

after_success:
    - if [ -z $DOCKER_NS ] ; then
        export DOCKER_NS=functions;
        fi
    - if [ ! -z "$TRAVIS_TAG" ] ; then 

        docker tag $DOCKER_NS/faas-swarm:latest-dev $DOCKER_NS/faas-swarm:$TRAVIS_TAG;
        echo $DOCKER_PASSWORD | docker login -u=$DOCKER_USERNAME --password-stdin;
        docker push $DOCKER_NS/faas-swarm:$TRAVIS_TAG;

        docker tag $DOCKER_NS/faas-swarm:latest-dev quay.io/$DOCKER_NS/faas-swarm:$TRAVIS_TAG;
        echo $QUAY_PASSWORD | docker login -u=$QUAY_USERNAME --password-stdin quay.io;
        docker push quay.io/$DOCKER_NS/faas-swarm:$TRAVIS_TAG;

        fi
        
